package com;

public class TestMain {

	static class A{
		String str;
	}
	
	public static void main(String[] args) {
		A a = new A();
		a.str = "main";
		System.out.println("main:"+a.str+"__address:"+a.hashCode());
		modifyData(a);
		System.out.println("main:"+a.str+"__address:"+a.hashCode());
	}
	
	private static void modifyData(A a){
//		a= new A();
		a.str="modifyData";
		System.out.println("main:"+a.str+"__address:"+a.hashCode());
	}
	
////	EBIZ_ASSET_ACCOUNT
////	EBIZ_ASSET_BALANCE
////	EBIZ_ASSET_DAILY
////	EBIZ_ASSET_DETAIL
////	EBIZ_ASSET_HIS
////	EBIZ_ASSET_INCOME
////	EBIZ_ASSET_PRINCIPAL
////	EBIZ_ASSET
//	EBIZ_AUDIT_CHECKRULE
//	EBIZ_BATCH_INFO     !
//	EBIZ_CHECKRULE_TEMPLATE
////	EBIZ_CREDIT
////	EBIZ_ELEC_VOUCHER
////	EBIZ_FUND_ACCOUNT
////	EBIZ_FUND_DIVIDEND_DETAIL
////	EBIZ_FUND_DIVIDEND
////	EBIZ_FUND_PAY_ACCOUNT
////	EBIZ_FUND_PURCHASE
////	EBIZ_FUND_SURRENDER		2
////	EBIZ_FUND_TRACE
////	EBIZ_FUND_VOL
//	EBIZ_MERCHANT_PROPERTY
//	EBIZ_OPER_HIS
////	EBIZ_ORDER_ACCOUNT
////	EBIZ_ORDER
//	EBIZ_ORDER_TYPE_PROPERTY
//	EBIZ_PAYMENT
////	EBIZ_POLICY_BNF
////	EBIZ_POLICY_INSURED
////	EBIZ_POLICY
//	EBIZ_PRODUCT_CATE
//	EBIZ_PRODUCT_CHECKRULE
//	EBIZ_PRODUCT_PROFIT
//	EBIZ_PRODUCT_PROPERTY
//	EBIZ_PRODUCT
//	EBIZ_PUBLIC_ALARM
//	EBIZ_PUBLIC_FEEBACK
//	EBIZ_PUBLIC_MENU
//	EBIZ_PUBLIC_MESSAGE_REMARK
//	EBIZ_PUBLIC_MESSAGE
//	EBIZ_PUBLIC_MSG_EXCHANGE
//	EBIZ_PUBLIC_PLATFORM
//	EBIZ_PUBLIC_RECEIVE_CONFIG
//	EBIZ_PUBLIC_USER
//	EBIZ_PWI_APPNT
//	EBIZ_PWI_BILL
//	EBIZ_PWI_CLAIM_IMAGE
//	EBIZ_PWI_CLAIM_POLICY
//	EBIZ_PWI_CLAIM
//	EBIZ_PWI_DAILY_SUMMARY
//	EBIZ_PWI_INSURED
//	EBIZ_PWI_POLICY
//	EBIZ_PWI_TOTAL_POLICY
////	EBIZ_SURRENDER_AUDIT_HIS
////	EBIZ_SURRENDER_AUDIT
////	EBIZ_SURRENDER_RETURN_HIS
////	EBIZ_SURRENDER		2
//	EBIZ_SY_BANKLOCATIONS
//	EBIZ_SY_BANKS
//	EBIZ_SY_STANDARDAREAS
//	EBIZ_THIRD_FILE
//	EBIZ_THIRD_FUND_CUST
//	EBIZ_THIRD_TRADE
////	EBIZ_TURN_PURCHASE
////	EBIZ_VIRTUAL
//	EBIZ_WORKING_DAYS
//	HUARUI8_FIRST_PURCHASE

}
